(define (cont-frac n d k)
  (define (cont-frac-rec i)
    (/ (n i)
       (+ (d i)
          (if (= i k)
            0
            (cont-frac-rec (+ 1 i))
          )
       )
    )
  )
  (cont-frac-rec 1.0)
)

(define (cont-fraction n d k)
  (define (cont-frac-iter i result)
    (if (= i 0)
      result
      (cont-frac-iter (- i 1)
                      (/ (n i)
                         (+ (d i) result)
                      )
      )
    )
  )
  (cont-frac-iter k 0.0)
)

(cont-frac (lambda (i) 1.0) (lambda (i) 1.0) 1000)
(cont-fraction (lambda (i) 1.0) (lambda (i) 1.0) 1000)
